### ISSUE TITLE
Todo by 7/29

### ISSUE THREAD

**Issue by juliev42** [juliev42/prerit-therapy-glove#1]
- [ ] Overall: Combine and filter data for touch, flex, and IMU sensors
- [x] -order parts and build 2nd prototype
- [ ] -combine sensor code into single file with bluetooth
- [ ] -choose and implement DSP for flex sensor noise reduction

- [ ] Overall: make a game for basic patient testing 
- [x] -make glove into a functional keyboard
- [ ] -research potential therapy games, figure out why push to market in US often fails
